### ISSUE TITLE
file_sync_client.cpp:503] protocol fault: stat response has wrong message id: 1279869254

### ISSUE THREAD

**Issue by mickelliu** [LmeSzinc/AzurLaneUncensored#1]
作者大大您好，

我是小白，第一次听说和接触adb，请问以下的error是有什么造成有头绪吗？...谢谢！

```
C:\platform-tools\AzurLaneUncensored>adb -s emulator-5554 push files /storage/emulated/0/Android/data/com.bilibili.azurlane
adb F 01-07 00:52:54 32216 32400 file_sync_client.cpp:503] protocol fault: stat response has wrong message id: 1279869254
```

`adb device` 是能看到东西的：
```
C:\platform-tools\AzurLaneUncensored>adb devices
List of devices attached
emulator-5554   device
```

其他：
windows cmd
adb从这下的[(https://developer.android.com/studio/releases/platform-tools)]，然后放到本仓库的clone里（懒得set path了）

**Comment by mickelliu** [comment]
啊解决了，我用的bluestack里面需要把adb设置打开，麻烦了！（虽然现在又出了file-sytem read only的问题，但至少可以连接到了）

**Comment by mickelliu** [comment]
```
C:\AzurLaneUncensored>adb -s emulator-5554 push files /storage/emulated/0/Android/data/com.bilibili.azurlane
files\: 84 files pushed, 0 skipped. 18.0 MB/s (101034047 bytes in 5.360s)
```

这算是成功了吗哈哈

**Comment by ICantInstall** [comment]
Hey, I've run into the same problem, could you say in english what you did to fix it? Thanks!

**Comment by mickelliu** [comment]
> Hey, I've run into the same problem, could you say in english what you did to fix it? Thanks!

You would need to check two things if you are using Blue stack (1) Settings>Devices>Enable root access (2) Settings>Advanced>Andriod Debug bridge>Connect to Andriod at 127.0.0.1:XXXX

If you don't mind I'm a little curious about why would you ever need to use this repo... are you playing on the CN server or are there also censorships on the international server as well?

**Comment by ICantInstall** [comment]
Thanks!
I just searched on duckduckgo and found this, I didn't realize this whole repo was chinese.
Have a nice day! :)
